#!/usr/bin/env python

import sys

x = sys.argv[1]
is_hex = False

if('0x' in x):
    is_hex = True

#
# if x starts with 0x, then it should be converted to binary/decimal
#
def num_to_binary(n, b=''):
    if(n <= 0):
        return b
    return num_to_binary(n/2, str(n % 2) + b)

def split(word): 
    return [char for char in word]  

def ch(c):
    if(c == 10): return 'A'
    if(c == 11): return 'B'
    if(c == 12): return 'C'
    if(c == 13): return 'D'
    if(c == 14): return 'E'
    if(c == 15): return 'F'
    return str(c)

def hc(c):
    c = c.upper()
    if(c == 'A'): return 10
    if(c == 'B'): return 11
    if(c == 'C'): return 12
    if(c == 'D'): return 13
    if(c == 'E'): return 14
    if(c == 'F'): return 15
    return int(c)

def num_to_hex(n, h=''):
    if(n <= 0):
        return h 
    return num_to_hex(n/16, ch(n % 16) + h)

def hex_to_number(n, h=0):
    n = n.replace('0x', '')
    chars = split(n)
    chars.reverse()
    power = 0
    for x in chars: 
        h = hc(x) * (16 ** power) + h
        power = power + 1
    return str(h)

if(is_hex):
    print('h' + hex_to_number(x))
else:
    print('b' + num_to_binary(int(x)))
    print('0x'  + num_to_hex(int(x)))
